apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_USER: root
  DB_PASSWORD: ""  # Change if you want a password
  MYSQL_ROOT_PASSWORD: ""  # Change if you want a password
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
