apiVersion: apps/v1
kind: Deployment
metadata:
  name: securejsonhome-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securejsonhome-web
  template:
    metadata:
      labels:
        app: securejsonhome-web
    spec:
      containers:
      - name: securejsonhome-web
        image: securejsonhome:20
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: securejsonhome-web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080
  selector:
    app: securejsonhome-web
